# Generated by Django 3.1.5 on 2021-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books", "0002_review")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="cover/"),
        )
    ]
