# Generated by Django 3.1.5 on 2021-01-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("books", "0003_book_cover")]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [("special_status", "Can read all books")],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        )
    ]
